### ISSUE TITLE
How to integrate this in the obsidian workflow?

### ISSUE THREAD

**Issue by 1C0D** [MateusMolina/obsidian-git-file-explorer#1]
I'm interested and just curious about how you are integrating this in your workflow in Obsidian ?
Can you do a short video showing what you can do from this, showing files in the explorer in each repo ? 
I mean, are you using other plugins on it ? Because I guess there is a goal to show them in the explorer.
I'm just a little bit confused about how to really use the possibilities your plugin is offering. 
Or are you planing to develop it further ?
(As a reference, doing the parallel with VSC, I can clearly understand how to use git info, and it's a great add indeed)
And in fact at first what is repo folder ? a clone of a plugin or others ?

**Comment by MateusMolina** [comment]
Hey,

I wrote this plugin because I wanted a way to easily commit to and sync git repositories inside my vault. For instance, each project/research I work on has its git repository. Say, I'm researching topic X; I could have a repository for it and each time I make some progress on that, I can easily commit it through the file explorer. If I work on the same repository on multiple machines, I could benefit from a remote, with which I can sync via the other widget available.

I don't know what you meant in your last question. A repo folder would be simply a folder with a git repository inside it. At least in my workflow, I don't manage plugins or any kind of code inside Obsidian at all.

But that doesn't mean this plugin couldn't help realize another type of workflow: anytime you need to manage a git repository inside your vault you could have this plugin interact with git for you.

Hope my answer helps clarify a bit my use-case.

**Comment by 1C0D** [comment]
thks for your answer
